CREATE DATABASE IF NOT EXISTS pruebas;
USE pruebas;
CREATE TABLE personas(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	number VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  code VARCHAR(255),
	PRIMARY KEY(id)
);
