CREATE DATABASE IF NOT EXISTS pruebas;
USE pruebas;
CREATE TABLE personas(
	id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL,
	telefono number(15) NOT NULL,
  	pass VARCHAR(255) NOT NULL,
	cpass VARCHAR(255) NOT NULL,
  	PRIMARY KEY(id)
);
